### PR TITLE
Support for Vivaldi

### PR DESCRIPTION
**Pull request by dann1**
vivaldi is chrome based

### CODE REVIEW

**Comment by skydrome** [comment]
hey there, thanks, but this is just a personal thing i use for myself. I would consider submitting pull requests to [this project](https://github.com/graysky2/profile-cleaner) which does the exact same thing.

**Comment by dann1** [comment]
No problem, the thing is I installed it from the AUR and since lots of
people use the AUR ...

**Comment by skydrome** [comment]
to be honest, this was more useful in much earlier browser versions. Chromium keeps its databases very optimized on its own now. There may be no real reason to ever need to run sqlite vacuum anymore.

**Comment by dann1** [comment]
Ok thanks for the tip

**Pull request closed without merging**
